dist: xenial
language: python
python: 3.7.2
before_install: ./.travis/travis_before_install.sh
install:
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - export TEST_DEBUG=1
  - py.test -v -s tests/test.py::TestInteractiveLightning::test_subscribe_channel_graph